# Generated by Django 2.2.26 on 2022-01-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.Customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Home appliances', 'Home appliances'), ('Laptops', 'Laptops'), ('Mobile Phones', 'Mobile Phones'), ('Headphones', 'Headphones'), ('Speakers', 'Speakers'), ('Desktops', 'Desktops'), ('Books', 'Books')], max_length=200, null=True),
        ),
    ]
