# Generated by Django 2.2.26 on 2022-01-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20220120_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
