# Generated by Django 4.0.1 on 2022-01-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
